# Generated by Django 6.0.3 on 2026-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_electricityusage_alter_foodpoll_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('maintenance', 'Maintenance'), ('rules', 'Hostel Rules'), ('event', 'Event'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
