# Generated by Django 5.2.7 on 2026-03-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricityusage',
            options={},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
